name: Feature
description: Nova funcionalidade do produto.
title: "feat: "
labels:
  - type/feature
  - status/triage
body:
  - type: markdown
    attributes:
      value: |
        Descreva o problema real primeiro. Solução sem problema definido é só hobby caro.
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: O que está quebrando na vida do usuário hoje?
      placeholder: "Ex: briefing não separa o que exige resposta do que é só leitura."
    validations:
      required: true
  - type: textarea
    id: outcome
    attributes:
      label: Resultado esperado
      description: Como fica quando estiver resolvido?
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Escopo
      description: O que entra e o que explicitamente não entra.
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
      description: Checklist objetivo de pronto.
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Prioridade
      options:
        - priority/p0
        - priority/p1
        - priority/p2
        - priority/p3
    validations:
      required: true
  - type: input
    id: target_version
    attributes:
      label: Target version
      placeholder: "Ex: 3.7.0"
