name: Spike
description: Investigação com prazo para reduzir incerteza.
title: "spike: "
labels:
  - type/spike
  - status/triage
body:
  - type: textarea
    id: question
    attributes:
      label: Pergunta a responder
    validations:
      required: true
  - type: textarea
    id: hypothesis
    attributes:
      label: Hipótese
    validations:
      required: true
  - type: input
    id: timebox
    attributes:
      label: Timebox
      placeholder: "Ex: 4h"
    validations:
      required: true
  - type: textarea
    id: deliverable
    attributes:
      label: Entregável
      description: Qual artefato concreto encerra o spike?
    validations:
      required: true
