name: Tech debt
description: Dívida técnica, refatoração ou melhoria de arquitetura.
title: "debt: "
labels:
  - type/debt
  - status/triage
body:
  - type: textarea
    id: debt
    attributes:
      label: Dívida atual
      description: Qual atalho técnico estamos pagando com juros?
    validations:
      required: true
  - type: textarea
    id: risk
    attributes:
      label: Risco de manter como está
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposta
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Critérios de aceite
      placeholder: |
        - [ ]
        - [ ]
    validations:
      required: true
