name: Validation
description: Validação cruzada de feature por outro agente.
title: "validation: "
labels:
  - type/validation
  - status/triage
body:
  - type: input
    id: source_pr
    attributes:
      label: PR de origem
      description: Link do PR que precisa ser validado.
      placeholder: "Ex: https://github.com/org/repo/pull/123"
    validations:
      required: true
  - type: input
    id: feature_issue
    attributes:
      label: Issue da feature
      description: Link da issue original da feature.
      placeholder: "Ex: https://github.com/org/repo/issues/456"
    validations:
      required: true
  - type: dropdown
    id: validating_agent
    attributes:
      label: Agente validador
      options:
        - agent/codex
        - agent/cowork
        - agent/gemini
    validations:
      required: true
  - type: textarea
    id: validation_scope
    attributes:
      label: Escopo da validação
      description: O que precisa ser conferido de forma objetiva.
      placeholder: |
        - Compatibilidade de comportamento:
        - Regressão funcional:
        - Limites/fallbacks:
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Resultado
      description: Registrar APPROVED/REJECTED com evidências.
      placeholder: |
        Resultado:
        Evidências:
        Riscos remanescentes:
